-- Schema for The EpicBook
CREATE DATABASE IF NOT EXISTS bookstore;
USE bookstore;

-- Authors table
CREATE TABLE IF NOT EXISTS Authors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  author_name VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Books table
CREATE TABLE IF NOT EXISTS Books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author_id INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  genre VARCHAR(100),
  stock INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES Authors(id)
);

-- Cart table
CREATE TABLE IF NOT EXISTS Cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  price DECIMAL(10, 2),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Cart-Book junction table
CREATE TABLE IF NOT EXISTS CartBook (
  id INT AUTO_INCREMENT PRIMARY KEY,
  CartId INT NOT NULL,
  BookId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CartId) REFERENCES Cart(id) ON DELETE CASCADE,
  FOREIGN KEY (BookId) REFERENCES Books(id) ON DELETE CASCADE
);

-- Checkout table
CREATE TABLE IF NOT EXISTS Checkout (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(50) DEFAULT 'pending',
  total DECIMAL(10, 2),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);